[package]
name = "audio"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui_extras = { version = "0.31.1", features = ["all_loaders"] }
egui_file = "0.22.1"
image = "0.25.6"
lofty = "0.22.4"
rodio = { version = "0.20.1", features = ["symphonia-aac", "symphonia-isomp4"] }
